export const movieArray = [
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
  {
    imageurl: [
      "https://m.media-amazon.com/images/M/MV5BMTcwYWFlNjItMmFiYi00NTIyLWJhNjQtNjIwNGI4YzllMDg4XkEyXkFqcGdeQXVyNjE5Mzc3NTE@._V1_UX182_CR0,0,182,268_AL_.jpg",
    ],
    genre: ["Comedy", "Romance"],
    imdbid: "tt9342356",
    title: "Back to Lyla",
    imdbrating: 7,
    released: 2022,
    type: "movie",
    synopsis:
      "After discovering he might die soon, a timid young man along with his estranged and outrageous childhood friends, embark on a quest for closure on why the love of his life left.",
  },
];

export const songObject = [
  {
    album_type: "single",
    total_tracks: 10,
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "PR",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/1WkykSHhndyQJcYNwL7zxY",
    },
    href: "https://api.spotify.com/v1/albums/1WkykSHhndyQJcYNwL7zxY",
    id: "1WkykSHhndyQJcYNwL7zxY",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273145eb25fb67e59a653f21ee8",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02145eb25fb67e59a653f21ee8",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851145eb25fb67e59a653f21ee8",
        width: 64,
      },
    ],
    name: "genre : sadboy",
    release_date: "2024-03-29",
    release_date_precision: "day",
    type: "album",
    uri: "spotify:album:1WkykSHhndyQJcYNwL7zxY",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6TIYQ3jFPwQSRmorSezPxX",
        },
        href: "https://api.spotify.com/v1/artists/6TIYQ3jFPwQSRmorSezPxX",
        id: "6TIYQ3jFPwQSRmorSezPxX",
        name: "mgk",
        type: "artist",
        uri: "spotify:artist:6TIYQ3jFPwQSRmorSezPxX",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6Xgp2XMz1fhVYe7i6yNAax",
        },
        href: "https://api.spotify.com/v1/artists/6Xgp2XMz1fhVYe7i6yNAax",
        id: "6Xgp2XMz1fhVYe7i6yNAax",
        name: "Trippie Redd",
        type: "artist",
        uri: "spotify:artist:6Xgp2XMz1fhVYe7i6yNAax",
      },
    ],
  },
  {
    album_type: "single",
    total_tracks: 10,
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "PR",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/1WkykSHhndyQJcYNwL7zxY",
    },
    href: "https://api.spotify.com/v1/albums/1WkykSHhndyQJcYNwL7zxY",
    id: "1WkykSHhndyQJcYNwL7zxY",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273145eb25fb67e59a653f21ee8",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02145eb25fb67e59a653f21ee8",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851145eb25fb67e59a653f21ee8",
        width: 64,
      },
    ],
    name: "genre : sadboy",
    release_date: "2024-03-29",
    release_date_precision: "day",
    type: "album",
    uri: "spotify:album:1WkykSHhndyQJcYNwL7zxY",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6TIYQ3jFPwQSRmorSezPxX",
        },
        href: "https://api.spotify.com/v1/artists/6TIYQ3jFPwQSRmorSezPxX",
        id: "6TIYQ3jFPwQSRmorSezPxX",
        name: "mgk",
        type: "artist",
        uri: "spotify:artist:6TIYQ3jFPwQSRmorSezPxX",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6Xgp2XMz1fhVYe7i6yNAax",
        },
        href: "https://api.spotify.com/v1/artists/6Xgp2XMz1fhVYe7i6yNAax",
        id: "6Xgp2XMz1fhVYe7i6yNAax",
        name: "Trippie Redd",
        type: "artist",
        uri: "spotify:artist:6Xgp2XMz1fhVYe7i6yNAax",
      },
    ],
  },
];
